### ISSUE TITLE
Modernigo de retformulara redaktilo

### ISSUE THREAD

**Issue by wdiestel** [revuloj/voko-araneo#3]
Rearanĝu la retformularan redaktilon iom:
- servu la enhavon per Ajax/XML, tiel la paĝo mem estas pli facile rearanĝebla
- ordigu la aranĝon de la butonoj
- navigado drv-drv... estu flanke de textarea
- uzu ekranklavaron laŭ revaj.steloj.de

**Comment by wdiestel** [comment]
Provizora interrezulto troviĝas ĉe https://github.com/revuloj/voko-araneo/tree/master/n1b

**Comment by wdiestel** [comment]
la malnovan vokomail.pl ni dividu en tri partojn:
- vokoktrlx.pl - por kontroli la sintakson de XML
- vokohtmlx.pl - por servi antarigardon en HTML
- vokomailx.pl por sendi XML al la redaktoservo

**Comment by reta-vortaro** [comment]
La kontrolo de referencoj malsukcesas ĉe subsnc, ekz. en artikolo "ten": `Referenco celas al "ten.0i.enmane_iun", kiu ne ekzistas en artikolo ten ...`

**Comment by wdiestel** [comment]
krom ekranklavaro la dieoj estas nun realigitaj en versio 1c
